export const LOGIN_SCREEN = "LOGIN_SCREEN"
export const SIGNUP_SCREEN1 = "SignUp_1"
export const SIGNUP_SCREEN2 = "SignUp_2"
export const SIGNUP_SCREEN3 = "SignUp_3"
export const SIGNUP_SCREEN4 = "SignUp_4"
